### PR TITLE
add metadata screen widget and new scene

### PR DESCRIPTION
**Pull request by argallegos**
This PR adds a new scene (06_CesiumMetadata) that displays metadata about selected buildings or tiles. Also included are the UMG widgets to display this metadata.

MetadataPicking

You must make sure you are using a version of the plugin from after the metadata functionality was merged ([b4e1b91](https://github.com/CesiumGS/cesium-unreal/commit/b4e1b9195eb01109668544de431157bf0e23daab) or later). 

To test it out, simply load the 06_CesiumMetadata scene and press play. Align the crosshairs in the center of the screen over a building, and click the left mouse button to view the metadata.

### CODE REVIEW

**Comment by kring** [comment]
Awesome, thanks @argallegos! Do you think it might be useful to put any of this in the plugin itself as a convenience for our users?

**Comment by argallegos** [comment]
@kring We certainly could, but it still would need more work - The widget currently only accomodates about as much metadata as is available in this specific tileset. We'd want to add a scroll bar and perhaps other functionality to make it more reusable. Shehzan and I discussed possibly creating new controls to allow users a free cursor for selecting buildings. 
Personally, I think it would be nice to include in the plugin properly, if we want to put the work in (Maybe another day's worth?)

**Comment by argallegos** [comment]
Updated this scene to improve the metadata UI and add a note like the rest of the Samples scenes. 

Here's the current note - 

image
@shehzan10 any suggestions for phrasing?

The UI is now more similar to CesiumJS.
image

The UI has been updated so that it collapses when there is no metadata, and has a scroll box when metadata exceeds length of the UI widget. 
image
metadataBox

The user can right-click to unlock the mouse in order to use the scroll bar. 

The only problem that I am aware of is that if the length of the metadata exceeds a certain point, the text will overlap - 
image
This isn't a super common issue, but I'm not sure the best way to resolve it. We could shrink the font of long text strings, but that will also look odd. 

@kring I think if we wanted to add this to the plugin, it's likely ready now. The only other thing that we would want would involve implementing a whole new player controller to make camera/mouse movement more similar to CesiumJS, which I think is outside of the scope of this. Honestly, though, I think it might be best to keep it here for now, and move it to the plugin if/when we implement a different player controller that makes use of it.

**Comment by kring** [comment]
> Honestly, though, I think it might be best to keep it here for now, and move it to the plugin if/when we implement a different player controller that makes use of it.

👍 

Thanks @argallegos!

**Pull request merged**
