### PR TITLE
Add Box Exluder sample

### PR DESCRIPTION
**Pull request by joseph-kaile**
Demonstrates the new Cesium Tile Excluder: https://github.com/CesiumGS/cesium-unreal/pull/1194

image

### CODE REVIEW

**Comment by kring** [comment]
@joseph-kaile it looks like you may have created the new level in UE 5.2? Really sorry, but it needs to be redone in UE 5.0. Older versions can't load levels saved in newer ones.

**Comment by kring** [comment]
Now that 5.3 is out, we could maybe get away with targetting 5.1, since we won't be able to publish the next version of the plugin to the Marketplace for v5.0 anyway. But if you're redoing it anyway, might as well target 5.0 if possible.

**Comment by joseph-kaile** [comment]
I converted the level to 5.0 with some improvements.

**Comment by kring** [comment]
Thanks @joseph-kaile!

**Pull request merged**
